### ISSUE TITLE
The rsync_serve LWRP is not writing to rsync.conf. You end up with a blank rsync.conf.

### ISSUE THREAD

**Issue by grahamja** [chef-cookbooks/rsync#18]
None of the data makes it from the LWRP to the rsync.conf. The tests for this cookbook are also failing for the same reason.

```
bundle exec kitchen test simple-centos-66
-----> Starting Kitchen (v1.4.1)
-----> Cleaning up any prior instances of <simple-centos-66>
-----> Destroying <simple-centos-66>...
       Finished destroying <simple-centos-66> (0m0.00s).
-----> Testing <simple-centos-66>
-----> Creating <simple-centos-66>...
       Bringing machine 'default' up with 'virtualbox' provider...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-rsync-simple-centos-66_default_1438641755854_61171
       ==> default: Fixed port collision for 22 => 2222. Now on port 2203.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 22 => 2203 (adapter 1)
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2203
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection timeout. Retrying...
           default: 
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default: 
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Checking for host entries
       ==> default: Setting hostname...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <simple-centos-66> created.
       Finished creating <simple-centos-66> (0m43.56s).
-----> Converging <simple-centos-66>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.3.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       Downloading Chef  for el...
       downloading https://www.chef.io/chef/metadata?v=&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
         to file /tmp/install.sh.2395/metadata.txt
       trying wget...
       url      https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-12.4.1-1.el6.x86_64.rpm
       md5      f09a9ae589bb9040232c600b008ef812
       sha256   95150a4b3c3b2313bd206876e09e2fcf742f2fa4611951d52c79225becb32928
       downloaded metadata file looks valid...
       downloading https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-12.4.1-1.el6.x86_64.rpm
         to file /tmp/install.sh.2395/chef-12.4.1-1.el6.x86_64.rpm
       trying wget...
       Comparing checksum with sha256sum...
       
       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
       
       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.
       
       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
       
       Installing Chef 
       installing with rpm...
       warning: /tmp/install.sh.2395/chef-12.4.1-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
       Preparing...                ########################################### [100%]
          1:chef                   ########################################### [100%]
       Thank you for installing Chef!
       Transferring files to <simple-centos-66>
       Starting Chef Client, version 12.4.1
       Creating a new client identity for simple-centos-66 using the validator key.
       [2015-08-03T22:43:51+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       [2015-08-03T22:43:51+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["fake::simple"]
       [2015-08-03T22:43:51+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       Synchronizing Cookbooks:
         - fake
         - rsync
       Compiling Cookbooks...
       Converging 4 resources
       Recipe: rsync::default
       
           - install version 3.0.6-12.el6 of package rsync
       Recipe: rsync::server
       
       
           - update content in file /etc/init.d/rsyncd from none to 1bfbf2
           --- /etc/init.d/rsyncd       2015-08-03 22:44:13.181073877 +0000
           +++ /tmp/chef-rendered-template20150803-2496-z4x1s2  2015-08-03 22:44:13.180073377 +0000
           @@ -1 +1,71 @@
           +#!/bin/sh
           +#
           +# Rsyncd init script
           +#
           +# chkconfig: 2345 98 02
           +# description: Remote file copy program daemon
           +#
           +# Source function library.
           +. /etc/init.d/functions
           +. /etc/sysconfig/network
           +
           +#
           +# Set default options.  Override the defaults and define
           +# custom options in /etc/sysconfig/rsyncd
           +#
           +OPTS=""
           +[ -f /etc/sysconfig/rsyncd ] && . /etc/sysconfig/rsyncd
           +
           +# Check that networking is configured.
           +[ ${NETWORKING} = "no" ] && exit 0
           +
           +function start {
           +  echo -n $"Starting rsyncd: "
           +  if [ $UID -ne 0 ]; then
           +    RETVAL=1
           +    failure
           +  else
           +    daemon /usr/bin/rsync --daemon $OPTS
           +    RETVAL=$?
           +    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/rsyncd
           +  fi;
           +  echo
           +  return $RETVAL
           +}
           +
           +function stop {
           +  echo -n $"Shutting down rsyncd:"
           +  if [ $UID -ne 0 ]; then
           +    RETVAL=1
           +    failure
           +  else
           +    killproc /usr/bin/rsync
           +    RETVAL=$?
           +    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/rsyncd
           +  fi;
           +  echo
           +  return $RETVAL
           +}
           +
       
           +start)
           +  start
           +;;
           +stop)
           +  stop
           +;;
           +restart)
           +  stop
           +  start
           +;;
           +status)
           +  status rsync
           +  exit $?
           +;;
           +*)
           +  echo "Usage: rsyncd {start|stop|restart|status}"
           +  exit 1
           +esac
           +
       
           - change mode from '' to '0755'
           - change owner from '' to 'root'
       
           - restore selinux security context
         * service[rsyncd] action enable (skipped due to only_if)
         * service[rsyncd] action start (skipped due to only_if)
       Recipe: fake::simple
         * rsync_serve[tmp] action add[2015-08-03T22:44:13+00:00] WARN: Cloning resource attributes for service[rsyncd] from prior resource (CHEF-3694)
       [2015-08-03T22:44:13+00:00] WARN: Previous service[rsyncd]: /tmp/kitchen/cache/cookbooks/rsync/recipes/server.rb:39:in `from_file'
       [2015-08-03T22:44:13+00:00] WARN: Current  service[rsyncd]: /tmp/kitchen/cache/cookbooks/rsync/providers/serve.rb:47:in `write_conf'
        (up to date)
       
       
           - update content in file /etc/rsyncd.conf from none to f57720
           --- /etc/rsyncd.conf 2015-08-03 22:44:13.350158375 +0000
           +++ /tmp/chef-rendered-template20150803-2496-zfv0dx  2015-08-03 22:44:13.350158375 +0000
           @@ -1 +1,6 @@
           +# Rsync Config file written by chef
           +#
           +
           +
       
           - change mode from '' to '0640'
           - change owner from '' to 'root'
       
       
         * service[rsyncd] action nothing (skipped due to action :nothing)
       
           - restart service service[rsyncd]
       
       Running handlers:
       Running handlers complete
       Chef Client finished, 4/5 resources updated in 24.783508016 seconds
       Finished converging <simple-centos-66> (1m6.30s).
-----> Setting up <simple-centos-66>...
       Finished setting up <simple-centos-66> (0m0.00s).
-----> Verifying <simple-centos-66>...
       Preparing files for transfer
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
       Successfully installed thor-0.19.0
Fetching: busser-0.7.1.gem (100%)
       Successfully installed busser-0.7.1
       2 gems installed
-----> Setting up Busser
       Creating BUSSER_ROOT in /tmp/verifier
       Creating busser binstub
       Installing Busser plugins: busser-bats
       Plugin bats installed (version 0.3.0)
-----> Running postinstall for bats plugin
       Installed Bats to /tmp/verifier/vendor/bats/bin/bats
       Suite path directory /tmp/verifier/suites does not exist, skipping.
       Transferring files to <simple-centos-66>
-----> Running bats test suite
 ✓ rsync is running
 ✗ rsync is serving /tmp
          (in test file /tmp/verifier/suites/bats/verify_running.bats, line 6)
            `rsync rsync://127.0.0.1 | grep "tmp"' failed
       
       2 tests, 1 failure
       !!!!!! Command [/tmp/verifier/vendor/bats/bin/bats /tmp/verifier/suites/bats] exit code was 1
>>>>>> Verify failed on instance <simple-centos-66>.
>>>>>> Please see .kitchen/logs/simple-centos-66.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE

sudo -E /tmp/verifier/bin/busser test
']
>>>>>> ----------------------
```

**Comment by grahamja** [comment]
Looks like the issue is actually with Chef 12.4.1, resource.action is returning an array instead of a symbol like it is supposed to.

**Comment by Raboo** [comment]
Is the chef-client bug reported then?

**Comment by Raboo** [comment]
Same problem with Chef 12.4.2
